name: animated_list_plus
description: A Flutter ListView that implicitly animates between the changes of
  two lists with the support to reorder its items.
version: 0.5.1
homepage: https://github.com/wwwdata/implicitly_animated_reorderable_list

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  async: ^2.8.1
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
